format = """
$all\
$line_break\
$env_var$character"""

[env_var.SQUAREBOX]
format = "[🟧📦](yellow)"

[container]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
