#!/usr/bin/env bash
set -euo pipefail

# Fetch latest versions of the Dockerfile-tier tools, download artifacts for
# both architectures, compute SHA256 checksums, and update checksums.txt
# and the Dockerfile ARGs.
#
# Optional tools installed by setup.sh and sqrbx-update track upstream latest
# at install time and are NOT pinned here (see setup.sh / squarebox-update.sh).

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Source shared tool library (for sb_get, sb_artifact, sb_url, sb_list_group)
export SB_TOOLS_YAML="${REPO_ROOT}/scripts/lib/tools.yaml"
source "${REPO_ROOT}/scripts/lib/tool-lib.sh"

# Pre-flight: check remaining GitHub API rate limit
_rate_info=$(curl -fsSL "https://api.github.com/rate_limit" 2>/dev/null) || true
_rate_remaining=$(echo "$_rate_info" | jq -r '.rate.remaining' 2>/dev/null) || true
_rate_limit=$(echo "$_rate_info" | jq -r '.rate.limit' 2>/dev/null) || true
if [[ "${_rate_remaining:-0}" =~ ^[0-9]+$ ]] && [ "$_rate_remaining" -lt 20 ]; then
	echo "Error: Only ${_rate_remaining}/${_rate_limit} GitHub API requests remaining." >&2
	exit 1
fi

# Strip leading 'v' from a tag
strip_v() { echo "${1#v}"; }

download_and_hash() {
	local url="$1" name="$2"
	curl -fsSLo "${WORK}/${name}" "$url"
	sha256sum "${WORK}/${name}" | awk '{print $1}'
}

echo "Fetching latest versions (Dockerfile tier)..."

# ── Fetch latest versions for dockerfile-group tools ──────────────────

declare -A VERSIONS

for tool in $(sb_list_group dockerfile); do
	prefix=$(sb_get "$tool" version_prefix)
	tag=$(sb_gh_latest_tag "$(sb_get "$tool" repo)")
	if [ -n "$prefix" ]; then
		VERSIONS[$tool]=$(strip_v "$tag")
	else
		VERSIONS[$tool]="$tag"
	fi
done

echo
echo "Versions:"
for tool in $(sb_list_group dockerfile); do
	printf "  %-12s %s\n" "$tool" "${VERSIONS[$tool]}"
done
echo

echo "Downloading artifacts and computing checksums..."

# ── Generate checksums.txt ────────────────────────────────────────────

cat > "${REPO_ROOT}/checksums.txt" << HEADER
# SHA256 checksums for Dockerfile binary tool downloads.
# Format: sha256  filename
# Generated by scripts/update-versions.sh — do not edit manually.
#
HEADER

emit() {
	local label="$1" url="$2" name="$3"
	local hash
	hash=$(download_and_hash "$url" "$name")
	echo "${hash}  ${name}" >> "${REPO_ROOT}/checksums.txt"
	echo "  ${label}: ${hash}  ${name}"
}

for tool in $(sb_list_group dockerfile); do
	ver="${VERSIONS[$tool]}"
	display=$(echo "$tool" | tr '-' ' ')
	echo "# ${display^} ${ver}" >> "${REPO_ROOT}/checksums.txt"

	artifact_amd64=$(sb_artifact "$tool" "$ver" amd64)
	artifact_arm64=$(sb_artifact "$tool" "$ver" arm64)
	url_amd64=$(sb_url "$tool" "$ver" amd64)
	url_arm64=$(sb_url "$tool" "$ver" arm64)

	emit "$tool amd64" "$url_amd64" "$artifact_amd64"
	emit "$tool arm64" "$url_arm64" "$artifact_arm64"
done

# ── Update Dockerfile ARGs ────────────────────────────────────────────

echo
echo "Updating Dockerfile..."

update_arg() {
	local name="$1" value="$2"
	sed -i "s|^ARG ${name}=.*|ARG ${name}=${value}|" "${REPO_ROOT}/Dockerfile"
}

update_arg DELTA_VERSION "${VERSIONS[delta]}"
update_arg YQ_VERSION "${VERSIONS[yq]}"
update_arg XH_VERSION "${VERSIONS[xh]}"
update_arg STARSHIP_VERSION "${VERSIONS[starship]}"
update_arg GLOW_VERSION "${VERSIONS[glow]}"
update_arg GUM_VERSION "${VERSIONS[gum]}"

echo
echo "Done. Review changes with: git diff"
