#!/usr/bin/env bash
set -euo pipefail

# Fetch latest versions of all pinned tools, download artifacts for both
# architectures, compute SHA256 checksums, and update checksums.txt,
# setup-checksums.txt, Dockerfile, and setup.sh.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# Source shared tool library (for sb_get, sb_artifact, sb_url, sb_list_group)
export SB_TOOLS_YAML="${REPO_ROOT}/scripts/lib/tools.yaml"
source "${REPO_ROOT}/scripts/lib/tool-lib.sh"

# Pre-flight: check remaining GitHub API rate limit
_rate_info=$(curl -fsSL "https://api.github.com/rate_limit" 2>/dev/null) || true
_rate_remaining=$(echo "$_rate_info" | jq -r '.rate.remaining' 2>/dev/null) || true
_rate_limit=$(echo "$_rate_info" | jq -r '.rate.limit' 2>/dev/null) || true
if [[ "${_rate_remaining:-0}" =~ ^[0-9]+$ ]] && [ "$_rate_remaining" -lt 20 ]; then
	echo "Error: Only ${_rate_remaining}/${_rate_limit} GitHub API requests remaining." >&2
	exit 1
fi

gh_latest_tag() {
	local repo="$1"
	local response http_code body
	response=$(curl -fsSL -w '\n%{http_code}' \
		"https://api.github.com/repos/${repo}/releases/latest" 2>/dev/null) || true
	http_code=$(echo "$response" | tail -1)
	body=$(echo "$response" | sed '$d')
	if [ "$http_code" = "403" ]; then
		echo "Error: GitHub API rate limit exceeded (${repo})." >&2
		exit 1
	elif [ "$http_code" != "200" ]; then
		echo "Error: GitHub API returned HTTP ${http_code} for ${repo}." >&2
		exit 1
	fi
	echo "$body" | jq -r '.tag_name'
}

# Strip leading 'v' from a tag
strip_v() { echo "${1#v}"; }

download_and_hash() {
	local url="$1" name="$2"
	curl -fsSLo "${WORK}/${name}" "$url"
	sha256sum "${WORK}/${name}" | awk '{print $1}'
}

echo "Fetching latest versions..."

# ── Fetch latest versions ─────────────────────────────────────────────
# Read repos from tools.yaml; handle version_prefix for tag→version stripping.

declare -A VERSIONS

for tool in $(sb_list_tools); do
	repo=$(sb_get "$tool" repo)
	prefix=$(sb_get "$tool" version_prefix)
	tag=$(gh_latest_tag "$repo")
	if [ -n "$prefix" ]; then
		VERSIONS[$tool]=$(strip_v "$tag")
	else
		VERSIONS[$tool]="$tag"
	fi
done

# Non-registry tools (not in tools.yaml)
GO_VERSION=$(curl -fsSL "https://go.dev/VERSION?m=text" | head -1)
if ! echo "$GO_VERSION" | grep -qE '^go[0-9]+\.[0-9]+'; then
	echo "Error: unexpected Go version format: '$GO_VERSION'" >&2; exit 1
fi

NVM_TAG=$(gh_latest_tag nvm-sh/nvm)
NVM_VERSION=$(strip_v "$NVM_TAG")

# Edit special handling: asset version may differ from tag
_edit_response=$(curl -fsSL -w '\n%{http_code}' \
	"https://api.github.com/repos/microsoft/edit/releases/latest" 2>/dev/null) || true
_edit_http=$(echo "$_edit_response" | tail -1)
if [ "$_edit_http" = "403" ]; then
	echo "Error: GitHub API rate limit exceeded (microsoft/edit assets)." >&2
	exit 1
elif [ "$_edit_http" != "200" ]; then
	echo "Error: GitHub API returned HTTP ${_edit_http} for microsoft/edit assets." >&2
	exit 1
fi
_edit_body=$(echo "$_edit_response" | sed '$d')
EDIT_ASSET_X86=$(echo "$_edit_body" | jq -r '.assets[].name' | grep 'x86_64-linux-gnu')
EDIT_ASSET_ARM=$(echo "$_edit_body" | jq -r '.assets[].name' | grep 'aarch64-linux-gnu')
EDIT_ASSET_VERSION=$(echo "$EDIT_ASSET_X86" | sed -E 's/^edit-([0-9]+\.[0-9]+\.[0-9]+)-.*/\1/')
export SB_ASSET_VERSION="$EDIT_ASSET_VERSION"

echo
echo "Versions:"
for tool in $(sb_list_tools); do
	printf "  %-12s %s\n" "$tool" "${VERSIONS[$tool]}"
done
printf "  %-12s %s\n" "go" "$GO_VERSION"
printf "  %-12s %s\n" "nvm" "$NVM_VERSION"
printf "  %-12s %s (asset: %s)\n" "edit" "${VERSIONS[edit]}" "$EDIT_ASSET_VERSION"
echo

echo "Downloading artifacts and computing checksums..."

# ── Generate checksums.txt (Dockerfile tools) ─────────────────────────

cat > "${REPO_ROOT}/checksums.txt" << HEADER
# SHA256 checksums for Dockerfile binary tool downloads.
# Format: sha256  filename
# Generated by scripts/update-versions.sh — do not edit manually.
#
HEADER

emit() {
	local label="$1" url="$2" name="$3"
	local hash
	hash=$(download_and_hash "$url" "$name")
	echo "${hash}  ${name}" >> "${REPO_ROOT}/checksums.txt"
	echo "  ${label}: ${hash}  ${name}"
}

emit_setup() {
	local label="$1" url="$2" name="$3"
	local hash
	hash=$(download_and_hash "$url" "$name")
	echo "${hash}  ${name}" >> "${REPO_ROOT}/setup-checksums.txt"
	echo "  ${label}: ${hash}  ${name}"
}

for tool in $(sb_list_group dockerfile); do
	ver="${VERSIONS[$tool]}"
	display=$(echo "$tool" | tr '-' ' ')
	echo "# ${display^} ${ver}" >> "${REPO_ROOT}/checksums.txt"

	artifact_amd64=$(sb_artifact "$tool" "$ver" amd64)
	artifact_arm64=$(sb_artifact "$tool" "$ver" arm64)
	url_amd64=$(sb_url "$tool" "$ver" amd64)
	url_arm64=$(sb_url "$tool" "$ver" arm64)

	emit "$tool amd64" "$url_amd64" "$artifact_amd64"
	emit "$tool arm64" "$url_arm64" "$artifact_arm64"
done

# ── Generate setup-checksums.txt ──────────────────────────────────────

cat > "${REPO_ROOT}/setup-checksums.txt" << HEADER
# SHA256 checksums for setup.sh downloads.
# Format: sha256  filename
# Generated by scripts/update-versions.sh — do not edit manually.
#
HEADER

for tool in $(sb_list_group setup); do
	ver="${VERSIONS[$tool]}"
	display=$(echo "$tool" | tr '-' ' ')

	# Special label for edit with asset version
	if [ "$tool" = "edit" ]; then
		echo "# Edit ${ver} (asset version ${EDIT_ASSET_VERSION})" >> "${REPO_ROOT}/setup-checksums.txt"
	else
		echo "# ${display^} ${ver}" >> "${REPO_ROOT}/setup-checksums.txt"
	fi

	artifact_amd64=$(sb_artifact "$tool" "$ver" amd64)
	artifact_arm64=$(sb_artifact "$tool" "$ver" arm64)
	url_amd64=$(sb_url "$tool" "$ver" amd64)
	url_arm64=$(sb_url "$tool" "$ver" arm64)

	emit_setup "$tool amd64" "$url_amd64" "$artifact_amd64"
	emit_setup "$tool arm64" "$url_arm64" "$artifact_arm64"
done

# NVM (not in tools.yaml — uses raw.githubusercontent.com, not GitHub releases)
echo "# NVM install script v${NVM_VERSION}" >> "${REPO_ROOT}/setup-checksums.txt"
emit_setup "nvm script" "https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh" "nvm-install-v${NVM_VERSION}.sh"

# Go (not in tools.yaml — uses go.dev, not GitHub releases)
echo "# Go ${GO_VERSION}" >> "${REPO_ROOT}/setup-checksums.txt"
emit_setup "go amd64" "https://go.dev/dl/${GO_VERSION}.linux-amd64.tar.gz" "${GO_VERSION}.linux-amd64.tar.gz"
emit_setup "go arm64" "https://go.dev/dl/${GO_VERSION}.linux-arm64.tar.gz" "${GO_VERSION}.linux-arm64.tar.gz"

# ── Update Dockerfile ARGs ────────────────────────────────────────────

echo
echo "Updating Dockerfile..."

update_arg() {
	local name="$1" value="$2"
	sed -i "s|^ARG ${name}=.*|ARG ${name}=${value}|" "${REPO_ROOT}/Dockerfile"
}

update_arg DELTA_VERSION "${VERSIONS[delta]}"
update_arg YQ_VERSION "${VERSIONS[yq]}"
update_arg LAZYGIT_VERSION "${VERSIONS[lazygit]}"
update_arg XH_VERSION "${VERSIONS[xh]}"
update_arg YAZI_VERSION "${VERSIONS[yazi]}"
update_arg STARSHIP_VERSION "${VERSIONS[starship]}"
update_arg GH_DASH_VERSION "${VERSIONS[gh-dash]}"
update_arg GLOW_VERSION "${VERSIONS[glow]}"
update_arg GUM_VERSION "${VERSIONS[gum]}"

# ── Update setup.sh versions ──────────────────────────────────────────

echo "Updating setup.sh..."

sed -i "s|^OPENCODE_VERSION=.*|OPENCODE_VERSION=\"${VERSIONS[opencode]}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^GO_VERSION=.*|GO_VERSION=\"${GO_VERSION}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^NVM_VERSION=.*|NVM_VERSION=\"${NVM_VERSION}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^MICRO_VERSION=.*|MICRO_VERSION=\"${VERSIONS[micro]}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^EDIT_VERSION=.*|EDIT_VERSION=\"${VERSIONS[edit]}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^EDIT_ASSET_VERSION=.*|EDIT_ASSET_VERSION=\"${EDIT_ASSET_VERSION}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^FRESH_VERSION=.*|FRESH_VERSION=\"${VERSIONS[fresh]}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^HELIX_VERSION=.*|HELIX_VERSION=\"${VERSIONS[helix]}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^NVIM_VERSION=.*|NVIM_VERSION=\"${VERSIONS[nvim]}\"|" "${REPO_ROOT}/setup.sh"
sed -i "s|^ZELLIJ_VERSION=.*|ZELLIJ_VERSION=\"${VERSIONS[zellij]}\"|" "${REPO_ROOT}/setup.sh"

echo
echo "Done. Review changes with: git diff"
